source 'https://github.com/CocoaPods/Specs.git'

target 'MZRelationalCollectionController', :exclusive => true do
  pod "MZRelationalCollectionController", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MZRelationalCollectionController", :path => "../"
end
