source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MZRelationalCollectionController_Example', :exclusive => true do
  pod "MZRelationalCollectionController", :path => "../"
end

target 'MZRelationalCollectionController_Tests', :exclusive => true do
  pod "MZRelationalCollectionController", :path => "../"

  
end
